### ISSUE TITLE
What license is this under?

### ISSUE THREAD

**Issue by mcisar** [petrjahoda/terminal_local_webservice#1]
Have used your prior version from tutorial rpi_kiosk_webservice which was under MIT license.  Looking at this newer version from your 2022 updated tutorial but notice you haven't posted a license.  Is this still under MIT license, or ???

Thanks
Mike

**Comment by petrjahoda** [comment]
Well, that is strange, but thank you for pointing out. Proper license added

**Comment by mcisar** [comment]
Thanks Petr.   See, there are some people who do actually pay attention to the licence   LOL

Mike
